---

- name: Installation apache
  apt:
    pkg: apache2
    state: installed

- name: Installation modules utiles
  apt:
    pkg: '{{ item }}'
    state: installed
  with_items:
    - libapache2-mod-wsgi

- name: Activation modules utiles
  apache2_module:
    name: '{{ item }}'
    state: present
  with_items:
    - rewrite
    - proxy
    - ssl
    - wsgi

- name: Suppression index par défaut
  file:
    path: /var/www/html/index.html
    state: absent

- name: Désactivation vhost par défaut
  template:
    src: etc_apache2_sites-enabled_000-default.conf.j2
    dest: /etc/apache2/sites-enabled/000-default.conf
  notify:
    - reload apache
