---

- name: Installation munin-node
  apt:
    pkg: munin-node
    state: installed

- name: Création du fichier de configuration
  template:
    src: etc_munin_munin-node.conf.j2
    dest: /etc/munin/munin-node.conf

- name: Activation plugins
  include: plugins.yml

- name: Redémarrage munin-node
  service:
    name: munin-node
    state: restarted
