---

- name: Installation munin
  apt:
    pkg: munin
    state: installed

- name: Création fichier de configuration
  template:
    src: etc_munin_munin.conf.j2
    dest: /etc/munin/munin.conf

- name: Vérification htpasswd
  shell: find /etc/apache2 -mindepth 1 -maxdepth 1 -name htpasswd.munin | wc -l
  register: munin_htpasswd_file
  changed_when: false
  when: munin_ssl_cert is defined

- name: Création htpasswd
  htpasswd:
    path: /etc/apache2/htpasswd.munin
    name: rcmunin
    state: present
    password: '{{ munin_htpassword }}'
  notify:
    - reload apache
  when: munin_htpasswd_file.stdout == '0' and munin_ssl_cert is defined

- name: Création config vhost apache SSL
  template:
    src: etc_apache2_sites-available_004-munin-ssl.conf.j2
    dest: /etc/apache2/sites-available/004-munin.conf
  notify:
    - reload apache
  when: munin_ssl_cert is defined

- name: Création config vhost apache
  template:
    src: etc_apache2_sites-available_004-munin-nossl.conf.j2
    dest: /etc/apache2/sites-available/004-munin.conf
  notify:
    - reload apache
  when: munin_ssl_cert is not defined

- name: Création lien config vhost apache
  file:
    src: /etc/apache2/sites-available/004-munin.conf
    path: /etc/apache2/sites-enabled/004-munin.conf
    state: link
  notify:
    - reload apache
