---

- name: Installation munin
  apt:
    pkg: munin
    state: installed

- name: Création fichier de configuration
  template:
    src: etc_munin_munin.conf.j2
    dest: /etc/munin/munin.conf

- name: Création htpasswd
  htpasswd:
    path: /etc/apache2/htpasswd.munin
    name: rcmunin
    state: present
  notify:
    - reload apache
  when: munin_ssl_cert is defined and munin_htpassword is not defined

- name: Création htpasswd
  htpasswd:
    path: /etc/apache2/htpasswd.munin
    name: rcmunin
    state: present
    password: '{{ munin_htpassword }}'
  notify:
    - reload apache
  when: munin_ssl_cert is defined and munin_htpassword is defined

- name: Création config vhost apache SSL
  template:
    src: etc_apache2_sites-enabled_004-munin-ssl.conf.j2
    dest: /etc/apache2/sites-enabled/004-munin.conf
  notify:
    - reload apache
  when: munin_ssl_cert is defined

- name: Création config vhost apache
  template:
    src: etc_apache2_sites-enabled_004-munin-nossl.conf.j2
    dest: /etc/apache2/sites-enabled/004-munin.conf
  notify:
    - reload apache
  when: munin_ssl_cert is not defined
