---

- name: Installation paquets utiles
  apt:
    pkg: '{{ item }}'
    state: installed
  with_items:
    - curl
    - git
    - gzip
    - htop
    - perl
    - python
    - python-passlib
    - subversion

- name: Creation groupe rcapps
  group:
    name: rcapps
    state: present
