---

- name: jessie repo backports included
  apt_repository:
    repo: '{{ item }}'
    state: present
  with_items:
   - "http://mirrors.online.net/debian jessie main contrib non-free"
   - "http://security.debian.org/ jessie/updates main contrib non-free"
   - "http://mirrors.online.net/debian jessie-backports main contrib non-free"

- name: Installation paquets utiles
  apt:
    pkg: '{{ item }}'
    state: installed
  with_items:
    - curl
    - git
    - gzip
    - htop
    - letsencrypt
    - perl
    - python
    - python-letsencrypt-apache
    - python-passlib
    - subversion
    - unzip

- name: Creation groupe rcapps
  group:
    name: rcapps
    state: present
