---

- name: Installation PHP
  apt:
    pkg: '{{ item }}'
    state: installed
  with_items:
    - libapache2-mod-php5
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-geoip
    - php5-mysqlnd

- name: Configuration PHP
  lineinfile:
    dest: /etc/php5/apache2/php.ini
    regexp: '^;always_populate_raw_post_data = -1'
    line: 'always_populate_raw_post_data = -1'
    state: present
  notify: reload apache

- name: Activation PHP
  apache2_module:
    name: '{{ item }}'
    state: present
  with_items:
    - php5
  notify: reload apache
